import { createUseStyles } from "react-jss";
import { theme } from "../../../theme /theme";
import { Theme } from "../../../theme /themeType";

export const useStyle = createUseStyles((theme:Theme)=>({
    MainContainer:{
        display:'flex',
        alignItems:'center',
        flexDirection:'column',
        gap:theme.spacing.s500,
        marginBottom:theme.spacing.s1600,
    },
    CardDiv:{
        height:'197px',
        width:'197px'
    },
    FashionImg:{
        width:'100%',
        height:'100%',
        objectFit:'cover',
        borderRadius:theme.spacing.s400
    },
    Title:{
        display:'flex',
        flexDirection:'column',
        alignItems:'center'
    },
    Wrapper:{
        display:'flex',
        gap:theme.spacing.s500
    },
    Model:{
        width:'1020px',
        height:'561px',
        left:'15%',
        top:'8%'
    },
    ModelImg:{
        width:'100%',
        height:'100%',
        objectFit:'cover'
    },
    ModelDiv:{
        width:'100%',
        maxWidth:'561px',
        height:'561px'
    },
    ModelDescription:{
        display:'flex',
        width:'100%',
        height:'355px',
        justifyContent:'space-between'
    },
    CardData:{
        width:'100%',
        maxWidth:'187px',
        height:'355px',
        display:'flex',
        alignItems:'center',
        textAlign:'center',
        flexDirection:'column',
        gap:theme.spacing.s300
    },
    RightDiv:{
        display:'flex',
    },
    Logo:{
        width:'100%',
        height:'100%',
        objectFit:'cover',
        borderRadius:theme.spacing.s400
    },
    LOgoDiv:{
        width:'187px',
        height:'250px'
    },
    RightSideDiv:{
        display:'flex',
        flexDirection:'column',
        padding:theme.spacing.s600,
        gap:theme.spacing.s500
    },
    InstaDiv:{
        display:'flex',
        alignItems:'center',
        gap:theme.spacing.s150,
        cursor:'pointer'
    }
}))